### ISSUE TITLE
Integrate core ui angular with asp.net core

### ISSUE THREAD

**Issue by pratishthap** [hozjanmarko/CoreUi_DotNetCore#1]
Hi.. i dont know how else to reach you.. please can you help me integrate core ui angular with asp.net core. Thanks a lot

**Comment by hozjanmarko** [comment]
Sorry, I'm just busy with work and family stuff, so I'm not following my
personal github feeds.

As a starter, look into the basics how aspnet core serves static files.
Then it's just as simple as copying your angular dist folder to the wwwroot
folder. As far development of the angular app goes, you can start ng serve
with proxy settings, so the api calls get redirected to the dotnetcore api
endpoint.

Get into the basics, then build up to porting existing apps to other
ecosystems.

Can't help you further.
Regards

15. mar. 2018 15:34 je oseba "pratishthap" <notifications@github.com>
napisala:

**Comment by pratishthap** [comment]
I integrated it in visual studio 2017 but my app does not load the template.. it shows nothing and no error.. so thats causing me trouble and i dnt know what is the issue

**Comment by hozjanmarko** [comment]
Here you go
